VACUUM FULL VERBOSE ANALYZE "MovingAverage";
VACUUM FULL VERBOSE ANALYZE "Message";
VACUUM FULL VERBOSE ANALYZE "Reaction";

--REINDEX TABLE "MovingAverage";
--REINDEX TABLE "Message";
--REINDEX TABLE "Reaction";

REINDEX DATABASE d39ddcnoeocgek;
